language: node_js
node_js:
  - node
cache:
  directories:
    - node_modules
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y build-essential libavahi-compat-libdnssd-dev
before_script:
  - npm install -g gulp-cli
script: gulp